### ISSUE TITLE
Crashing Every time in Mob smash horde battle

### ISSUE THREAD

**Issue by yoshi453** [masagrator/SaltyNX#10]
Sorry about that IM new here. I meant to open but yeah. Squad Strike and classic mode and Mob smash. horde battle it will 80% chance crash the game using SaltyNX  What should i do to fix the issues?

**Comment by masagrator** [comment]
Still don't know anything about your CFW environment, used plugins, what game are you talking about, etc. Write everything that can be helpful.

**Comment by Crashdummyy** [comment]
Update your sigpatches.
I resolved the problem by updating atmosphere and sigpatches

( I'm on HOS 10.0.2 btw )

**Comment by masagrator** [comment]
sigpatches have nothing to do with this.

**Comment by masagrator** [comment]
Closing issue because of no resposne over several months.
