### ISSUE TITLE
Super Mario 3D All Stars crashing

### ISSUE THREAD

**Issue by Le0xFF** [masagrator/SaltyNX#11]
Hello there, the game keeps crashing for me when I try to exit from one of the game pressing the minus button.
Also, Super Mario 64 won't start at all.

I also tried to add the TitleIDs to the exception.txt file but still no luck.
```
; Super Mario 3D All Stars
010049900F546000
010049900F546001
010049900F546002
010049900F546003
```

But if I disable SaltyNX I have no more crashes at all.

I'm currently using:
* **System Update**: 10.2.0
* **Atmosphère**: 0.14.4
* **SaltyNX**: 0.3.2a
    * **NX-FPS**: 0.3

Here's my erpt and fatal reports, hope they could help.
[reports.zip](https://github.com/masagrator/SaltyNX/files/5244691/reports.zip)

**Comment by masagrator** [comment]
You forgot to add X at the beginning of titleid

So it should be

```
; Super Mario 3D All Stars
X010049900F546000
X010049900F546001
X010049900F546002
X010049900F546003
```

This way Core won't be loaded at all for this titleids

**Comment by Le0xFF** [comment]
Even with the X at the beginning I have the same issue, kinda strange

**Comment by masagrator** [comment]
1. Do you have any other sysmodules?
2. Do you have any other plugins?

**Comment by Le0xFF** [comment]
1. The other sysmodules I have are:
    * [Fizeau](https://github.com/averne/Fizeau);
    * [bitmap-printer](https://github.com/HookedBehemoth/bitmap-printer/);
    * [sys-clk](https://github.com/retronx-team/sys-clk);
    * [ReiNX-Spoofer](https://git.nicholemattera.com/NicholeMattera/ReiNX-Spoofer) (I don't know if this could cause any issue).
2. No other plugins.

**Comment by masagrator** [comment]
It may be emuiibo. I heard from some people it has compability issue with SaltyNX, but never can find what is the issue here. I have tried once to use emuiibo with SaltyNX and never got an issue. Maybe it needs game with emuiibo to actually show itself. I will try to check it sometime later when weather will fricking chill.
