### ISSUE TITLE
Game Crashes Every Time I Use Jigglypuff Back Air

### ISSUE THREAD

**Issue by Omalight** [masagrator/SaltyNX#12]
Hello. I'm relatively new to modding smash, but I've noticed that every time I boot up smash and reads SaltyNX in the corner, if I use jigglypuff back air, my game will crash. I tried removing all of the mods I have installed to see if it was just a problematic mod, but even when there are no mods installed in either arcropolis, skyline, or saltynx, the game will still crash if I use Jigglypuff back air as long as the saltynx logo is shown on the title screen. Im not sure if it's just an issue with my files, but I've tried multiple things to find the source of the issue, and it's lead me to believe that salryNX is the thing to crash my game if I use that one specific move.

**Comment by masagrator** [comment]
>  I use Jigglypuff back air as long as the saltynx log

There is no "SaltyNX logo", so i don't know what are you talking about.
And SaltyNX is not doing anything in running game. After plugin js loaded SaltyNX deletes debugger from game and allows game to run. Only plugin remains. So it's the plugin issue. Probly not compatible with version of game you are using.
