### ISSUE TITLE
Crash on starting Immortals Fenyx Rising when SaltyNX is enabled.

### ISSUE THREAD

**Issue by auyx** [masagrator/SaltyNX#13]
Game crashes to a "this software closed because an error occurred" message after selecting your profile.

**Comment by masagrator** [comment]
I'm aware of situation. Need to get game, do some tests and in case include it in exceptions.txt

To block game from using plugins put titleid to `exceptions.txt`

**Comment by zleeven** [comment]
[exceptions.txt](https://github.com/masagrator/SaltyNX/files/5646392/exceptions.txt)
here is a exception.txt with the game titleid, I have already text it and it working, just drop it on saltysd folder, for anyone that want it. also masagrator keep up the great work, hope you get this game working soon.

**Comment by masagrator** [comment]
I won't fix it, because issue is in SaltyNX entire design. Plugin loading is intrusive (using svc only instead of mix svc + dedicated HOS system calls) and breaks memory management. Most games are recovering from this, but some not - like this game.

**Comment by machGhosTine** [comment]
> 
> 
> [exceptions.txt](https://github.com/masagrator/SaltyNX/files/5646392/exceptions.txt)
> here is a exception.txt with the game titleid, I have already text it and it working, just drop it on saltysd folder, for anyone that want it. also masagrator keep up the great work, hope you get this game working soon.

this actually worked for me, I'm on fw 11/ams .16/latest patches

**Comment by masagrator** [comment]
Added Immortals to exceptions.txt that is now part of 0.4.0a
