### ISSUE TITLE
Hi, saltynx elf mods are not loading

### ISSUE THREAD

**Issue by lucas55555** [masagrator/SaltyNX#16]
[saltysd.log](https://github.com/masagrator/SaltyNX/files/6120340/saltysd.log)

Hi! im sorry if this is a bit intrusive, or if this problem has been solved, i was just interested in trying to understand wich is the problem in my setup, Thank you so much in advance fella

Here is my log, also i have the saltynx tool and it says saltynx is working after just booting, but after starting smash and checking again, it says its not recognised. 

I have:

Atmos 18.1 
Hekate 5.5.4
FW 11.0.1
Arcropolis 1.0.1

i used to be at FW 10.2.0 and using Salty 2.1 ver and it worked normally

**Comment by masagrator** [comment]
1. There is no SaltyNX 2.1, dunno about which version you are talking about
2. You have two SaltyNX versions working simultanously and they are eating each other. One is very old versions from time, when Spawner existed. Delete whole SaltySD folder, delete folders 01000000534c56 and 00000000534c56 from atmosphere/contents and install again newest SaltyNX version.

Beside I don't recommend using SaltyNX in combination with Acropolis. They may also eat each other and logs won't show anything.

**Comment by lucas55555** [comment]
Thank you a lot!
