### ISSUE TITLE
wrong file loaded

### ISSUE THREAD

**Issue by Shaunathanz** [masagrator/SaltyNX#18]
I thought I was losing my mind for a second because I wasn't getting NX-FPS to load. Turned out, the problem was caused by macOS' index files

`SaltySD: loading sdmc:/SaltySD/plugins/NX-FPS.elf, size 0x14f88
SaltySD: Search for size e000
SaltySD: Found free address space at bf0658000, size e000
SaltySD: cmd 1 handler, proc handle 2e0007, heap 65b6c8d000, path ._NX-FPS.elf
SaltySD: loading sdmc:/SaltySD/plugins/._NX-FPS.elf, size 0x1000`

Paths beginning with "._" should be ignored.

**Comment by masagrator** [comment]
I won't add more code because Mac OS does stupid shit.
I am sure mac os has multiple ways to block indexing certain paths/drives.
