### ISSUE TITLE
The FIFA20 crash game

### ISSUE THREAD

**Issue by MythraUwU** [masagrator/SaltyNX#2]
The FIFA20 crash game after choosing a user, here is the image of the crash:
https://cdn.discordapp.com/attachments/688808212568473636/688963129971179581/JPEG_20200315_222218.jpg

When I remove "/amosphere/kips/saltysd_spawner.kip" the game works normally. To do the test I have removed all the sys-modules to rule out conflicts with third party homebrew.

Thanks for everything.

EDIT: I use Atmosphere 0.10.4 and Firmware 9.2 and use ur last versión Staly: SaltyNX 0.1.2a.

**Comment by masagrator** [comment]
Yes, I got confirmation that after checking server status it abruptly exits. 
Don't know if this is heap related, game is added to exceptions.
Thanks for your contribution. Can't resolve it for now.
