### ISSUE TITLE
The lastest firmware (13.2) + atmosphere (1.2.5) broke the addon

### ISSUE THREAD

**Issue by gcseed** [masagrator/SaltyNX#21]
The FPS no longer shows correctly in game. Was fine before on 13.1 and 1.2.4 or lower. 
Please advice, thank you very much!

**Comment by masagrator** [comment]
There was nothing in Atmosphere and FW update that could brake it.
Better check if you didn't break anything when updating Atmosphere.

**Comment by gcseed** [comment]
> There was nothing in Atmosphere and FW update that could brake it. Better check if you didn't break anything when updating Atmosphere.

Thank you for the swift reply! Can confirm that the latest Atmosphere (1.2.5) did overwrite the settings under 0000000000534C56 folder. Replacing it with the latest files included in SaltyNX-0.4.0a-hotfix solved the problem -- thanks again!
