### ISSUE TITLE
Mario Strikers: Battle League leads to crash on launch. (1.0.0, 

### ISSUE THREAD

**Issue by JonJaded** [masagrator/SaltyNX#23]
Add to exceptions.txt

```
;Mario Strikers: Battle League
;1.0.0 crash on boot
010019401051C000
```
Latest SaltyNX
Atmosphère 1.3.2
FW 14.1.1

**Comment by masagrator** [comment]
Yeah, I heard complaints about this game. I will test it myself to be sure it's not some race condition

**Comment by masagrator** [comment]
Added
