### ISSUE TITLE
Crash Donkey Kong Country Tropical Freeze

### ISSUE THREAD

**Issue by JuniorPassos** [masagrator/SaltyNX#29]
For some reason DK is crashing when SaltyNX is activated.
Tested on AMS 1.5.3 and pre-release 1.5.4

It was necessary to manually add this information below in the exceptions.txt

;Donkey Kong Country: Tropical Freeze
;1.0.0 - 1.0.2 crash on loading
X0100C1F0051B6000

**Comment by 760194962** [comment]
still same? unable to fix?

**Comment by JuniorPassos** [comment]
> still same? unable to fix?

I have already given the answer on how to fix the problem by editing the exceptions.txt file and adding the information above.

**Comment by masagrator** [comment]
It works for me :tm:
