### ISSUE TITLE
you need a toolbox.json

### ISSUE THREAD

**Issue by fennectech** [masagrator/SaltyNX#3]
You need a toolbox.json for tools like kosmos toolbox and sysmodules overlay to manage this    This one will work for you
```
{
  "name": "SaltyNX",
  "tid": "0100000000534C56",
  "requires_reboot": false
}
```

**Comment by masagrator** [comment]
This is titleid of spawner. It's killed after loading SaltySD_Proc, so only what this would do is prevent sysmodule from loading at boot. 

SaltySD_Proc has different titleid
```
0100000000535344
```
 and Idk what would happen if it will be disabled when is in memory.

I will check if it's viable to add both or only Spawner.
```{
  "name": "SaltyNX",
  "tid": "0100000000534C56",
  "requires_reboot": true
}
```
```{
  "name": "SaltyNX",
  "tid": "0100000000535344",
  "requires_reboot": false
}
```

**Comment by fennectech** [comment]
if the spawner is disabled while its in memory it just wont come back next boot

**Comment by masagrator** [comment]
https://github.com/masagrator/SaltyNX/releases/tag/0.2.0a
