### ISSUE TITLE
Crash when building with latest devkitARM SDK and libnx4.4.2

### ISSUE THREAD

**Issue by zdm65477730** [masagrator/SaltyNX#31]
If build the SaltyNX, NX-FPS, and ReverseNX-RT with latest devkitARM and libnx4.4.2, it will crash when reopen the game.

**Comment by zdm65477730** [comment]
The issue seems relate to the latest Atmosphere 1.5.3/1.5.4, since it built with latest devkitARM .
And from the release note of Atmosphere, we can find it brings new GCC13/newlib 4.3.0(in devkitARM).

**Comment by monstrosities** [comment]
I saw experienced some strange crashing when building some other homebrew with latest tools and libraries also, so I don't think this is exclusive to SaltyNX.

**Comment by zdm65477730** [comment]
> I experienced some strange crashing in other homebrew when compiled with latest tools and libraries also, so I don't think this is exclusive to SaltyNX.

No, it is relate to SaltyNX toolset only, I suspect it relate to the shared memory solution in those toolset.
The other homebrew or tesla overlays did not see such issue.

**Comment by monstrosities** [comment]
> > I experienced some strange crashing in other homebrew when compiled with latest tools and libraries also, so I don't think this is exclusive to SaltyNX.
> 
> No, it is relate to SaltyNX toolset only, I suspect it relate to the shared memory solution in those toolset. The other homebrew or tesla overlays did not see such issue.

It's not, I experienced this with compiling an old homebrew called TriPlayer for example, with crashes occuring when certain operations were conducted from the overlay. I also experienced it with an older version of SimpleModManager when exiting.

As soon as I rolled back to the versions I compiled with libnx 4.3.0 all was fine.

**Comment by zdm65477730** [comment]
I

> > > I experienced some strange crashing in other homebrew when compiled with latest tools and libraries also, so I don't think this is exclusive to SaltyNX.
> > 
> > 
> > No, it is relate to SaltyNX toolset only, I suspect it relate to the shared memory solution in those toolset. The other homebrew or tesla overlays did not see such issue.
> 
> It's not, I experienced this with compiling an old homebrew called TriPlayer for example, with crashes occuring when certain operations were conducted from the overlay. I also experienced it with an older version of SimpleModManager when exiting.
> 
> As soon as I rolled back to the versions I compiled with libnx 4.3.0 all was fine.

It's not the same issue. All homebrew applications and tesla overlays I built with latest libnx and devkitARM are works really fine.
I don't use TriPlayer and SimpleModManager, but I built for more then 15+ homebrew and tesla overlays, they works as expected. The issue you mentioned here is not relate to game re-open crash.

**Comment by monstrosities** [comment]
> I
> 
> > > > I experienced some strange crashing in other homebrew when compiled with latest tools and libraries also, so I don't think this is exclusive to SaltyNX.
> > > 
> > > 
> > > No, it is relate to SaltyNX toolset only, I suspect it relate to the shared memory solution in those toolset. The other homebrew or tesla overlays did not see such issue.
> > 
> > 
> > It's not, I experienced this with compiling an old homebrew called TriPlayer for example, with crashes occuring when certain operations were conducted from the overlay. I also experienced it with an older version of SimpleModManager when exiting.
> > As soon as I rolled back to the versions I compiled with libnx 4.3.0 all was fine.
> 
> It's not the same issue. All homebrew applications and tesla overlays I built with latest libnx and devkitARM are works really fine. I don't use TriPlayer and SimpleModManager, but I built for more then 15+ homebrew and tesla overlays, they works as expected. The issue you mentioned here is not relate to game re-open crash.

I didn't say it was "game re-open crash", I said that compiling certain homebrew with the latest tools is causing unexpected crashing and it could be related. I compiled many myself too which is how I found these issues.

**Comment by zdm65477730** [comment]
> > I
> > > > > I experienced some strange crashing in other homebrew when compiled with latest tools and libraries also, so I don't think this is exclusive to SaltyNX.
> > > > 
> > > > 
> > > > No, it is relate to SaltyNX toolset only, I suspect it relate to the shared memory solution in those toolset. The other homebrew or tesla overlays did not see such issue.
> > > 
> > > 
> > > It's not, I experienced this with compiling an old homebrew called TriPlayer for example, with crashes occuring when certain operations were conducted from the overlay. I also experienced it with an older version of SimpleModManager when exiting.
> > > As soon as I rolled back to the versions I compiled with libnx 4.3.0 all was fine.
> > 
> > 
> > It's not the same issue. All homebrew applications and tesla overlays I built with latest libnx and devkitARM are works really fine. I don't use TriPlayer and SimpleModManager, but I built for more then 15+ homebrew and tesla overlays, they works as expected. The issue you mentioned here is not relate to game re-open crash.
> 
> I didn't say it was "game re-open crash", I said that compiling certain homebrew with the latest tools is causing unexpected crashing and it could be related. I compiled many myself too which is how I found these issues.

OK, but all applications and tesla overlays I built works fine, maybe it's the imcompatiable issue of those homebrew you mentioned above, maybe some adaptions need to be done.

**Comment by monstrosities** [comment]
> > > I
> > > > > > I experienced some strange crashing in other homebrew when compiled with latest tools and libraries also, so I don't think this is exclusive to SaltyNX.
> > > > > 
> > > > > 
> > > > > No, it is relate to SaltyNX toolset only, I suspect it relate to the shared memory solution in those toolset. The other homebrew or tesla overlays did not see such issue.
> > > > 
> > > > 
> > > > It's not, I experienced this with compiling an old homebrew called TriPlayer for example, with crashes occuring when certain operations were conducted from the overlay. I also experienced it with an older version of SimpleModManager when exiting.
> > > > As soon as I rolled back to the versions I compiled with libnx 4.3.0 all was fine.
> > > 
> > > 
> > > It's not the same issue. All homebrew applications and tesla overlays I built with latest libnx and devkitARM are works really fine. I don't use TriPlayer and SimpleModManager, but I built for more then 15+ homebrew and tesla overlays, they works as expected. The issue you mentioned here is not relate to game re-open crash.
> > 
> > 
> > I didn't say it was "game re-open crash", I said that compiling certain homebrew with the latest tools is causing unexpected crashing and it could be related. I compiled many myself too which is how I found these issues.
> 
> OK, but all applications and tesla overlays I built works fine, maybe it's the imcompatiable issue of those homebrew you mentioned above, maybe some adaptions need to be done.

Maybe. I used exactly the same codebase, the only difference is that they were compiled with the latest devkitARM and libnx, that's why I commented here since you specifically mentioned "latest devkitARM SDK and libnx4.4.2".

**Comment by masagrator** [comment]
libnx version doesn't matter as SaltyNX is using it's own old libnx_min instead.

**Comment by masagrator** [comment]
And what games have you tested. If ToTK and any game after, that usually means you have too many sysmodules installed.

**Comment by masagrator** [comment]
I can only say that's not an issue with devkit as SaltyNX 0.6 works the same as previous versions on 16.0.0 + Atmo 1.5.2

**Comment by masagrator** [comment]
And hopefully you are talking about compiling unmodified source code and not your forks @zdm65477730

**Comment by zdm65477730** [comment]
> And what games have you tested. If ToTK and any game after, that usually means you have too many sysmodules installed because of system memory manipulation done by Atmosphere since 1.5.4 to support ToTK mods

Yes, after upgrade to Atmo 1.5.3 or above, and build with latest devkit, you can find the issue will happen. If you stay at Atom 1.5.2, the issue does not be seen.

**Comment by zdm65477730** [comment]
> And hopefully you are talking about compiling unmodified source code and not your forks @zdm65477730

I tested with your code, not my fork, the issue are the same.

**Comment by masagrator** [comment]
And did you uninstall all unnecessary custom sysmodules? 1.5.3 also reduced free system memory for sysmodules.

**Comment by monstrosities** [comment]
I don't understand why you keep specifying what you built with, are you saying that you compiled the same versions with an older devkit and they work fine? So unclear.

**Comment by monstrosities** [comment]
Sorry for commenting in the first place @masagrator 

The way he wrote this issue was really misleading.

**Comment by zdm65477730** [comment]
> And did you uninstall all unnecessary custom sysmodules? 1.5.3 also reduced free system memory for sysmodules.
> 
> Test only with Tesla + SaltyNX

I'll have a test, will feedback you later~ Thanks!

**Comment by zdm65477730** [comment]
We tested with:
contents: 0000000000534C56、420000000007E51A
.overlays: FPSLocker.ovl、ovlmenu.ovl、ovl-sysmodules.ovl、ReverseNX-RT.ovl
And remove all the other tesla overlays, cheats/MODs in contens, and it still crash when the 2nd time open the game.

**Comment by masagrator** [comment]
Does the same issue happen by downloading my latest releases instead of compiling them yourself?

**Comment by zdm65477730** [comment]
> Does the same issue happen by downloading my latest releases instead of compiling them yourself?

No, your latest release works well, did you build them(ReverseNX-RT.elf, NX-FPS.elf and SaltyNX.elf) with the old devkitARM SDK?

**Comment by masagrator** [comment]
I have build them with newest devkitA64 through WSL Ubuntu. I found only recently that `rules` were recently updated, but I guess this shouldn't affect result of compilation.

**Comment by masagrator** [comment]
Compiled with newest stuff and still no issues. I remember having issues with skyline plugins at one point with unwinding, but now there is no issue whatsoever when compiling. I guess we can close this.
