### ISSUE TITLE
The Lara Croft Collection closes app when SaltyNX is enabled

### ISSUE THREAD

**Issue by cucholix** [masagrator/SaltyNX#32]
The Lara Croft Collection | ver. 1.1_65791
TID: 010079C017F5E000
SaltyNX 0.6.0

The software closes after the selection game screen, disabling SaltyNX allows to boot the games normally. 
It doesn't help put the game in the exception.txt list 

[01688163673_010079c017f5e002.log](https://github.com/masagrator/SaltyNX/files/11923550/01688163673_010079c017f5e002.log)
[saltysd.log](https://github.com/masagrator/SaltyNX/files/11923551/saltysd.log)
[saltysd_core.log](https://github.com/masagrator/SaltyNX/files/11923552/saltysd_core.log)

**Comment by masagrator** [comment]
https://github.com/masagrator/SaltyNX/pull/33
