### ISSUE TITLE
Crash in AMS15.5.5,HOS16.1.0

### ISSUE THREAD

**Issue by Retr0Jak0be** [masagrator/SaltyNX#34]
When you reboot and start a game,it is nothing wrong.But if you switch to another game,boom!system error！Have to reboot

**Comment by masagrator** [comment]
My guess: you have too many custom sysmodules installed.

**Comment by Retr0Jak0be** [comment]
> My guess: you have too many custom sysmodules installed.

OK,i wii have a try,thanks.

**Comment by martixjohn** [comment]
same issue

**Comment by masagrator** [comment]
> same issue

This is how I see your contribution to this issue
![573](https://github.com/masagrator/SaltyNX/assets/8557858/32c224b0-0e8a-430e-bd7a-5dbee345581f)

Read my answer and figure out what you can do to test if this is it or not.

**Comment by martixjohn** [comment]
> > same issue
> 
> This is how I see your contribution to this issue ![573](https://user-images.githubusercontent.com/8557858/265214736-32c224b0-0e8a-430e-bd7a-5dbee345581f.jpg)
> 
> Read my original answer and figure out what you can do.

appreciate

**Comment by Panikk11503** [comment]
i will be the most helpful by telling you i am also having the same issue and am running basically nothing except sys clock and the pieces needed for fps-locker to run.  atmosphere 1.5.5 crash program 0000000000534C56 when trying to change game.  it will always boot the first game no problem.

**Comment by masagrator** [comment]
Ok, reproduced the issue. It all come down to not having enough memory reserved. Expanded available memory by 128kB and it works fine for now. I'm uploading here for tests, write if this will solve your issues.
[SaltyNX-test.zip](https://github.com/masagrator/SaltyNX/files/12567794/SaltyNX-test.zip)

**Comment by Retr0Jak0be** [comment]
Sorry,i have gone to college now and did not bring my switch,so sad

**Comment by Panikk11503** [comment]
i wrote a comment originally outlaying how i was having the problem as well but i don't use this site that much and was honestly a little put off by the reaction to people saying they were having the problem so i just deleted my comment so i wouldn't get flamed.  anyways i don't have a crash anymore going from one game to another anymore.  seems resolved for me at least.

**Comment by masagrator** [comment]
> i wrote a comment originally outlaying how i was having the problem as well but i don't use this site that much and was honestly a little put off by the reaction to people saying they were having the problem so i just deleted my comment so i wouldn't get flamed. anyways i don't have a crash anymore going from one game to another anymore. seems resolved for me at least.

Still I got an e-mail with your message, so deleting messages is pretty pointless if you wanted to avoid me reading your message. And it seems you don't understand what was the difference between your post and that guy's worthless post.

I will treat this as fixed.

https://github.com/masagrator/SaltyNX/releases/tag/0.6.1
