### ISSUE TITLE
Company of heroes collection crashes on launch with SaltyNX enabled

### ISSUE THREAD

**Issue by Sanicle87** [masagrator/SaltyNX#38]
Tested with the base game under firmware 16.1, AMS 1.5.5 and Hekate 6.0.7

Game works fine after a reboot with SaltyNX disabled under sysmodules

**Comment by Xalavar** [comment]
> Tested with the base game under firmware 16.1, AMS 1.5.5 and Hekate 6.0.7
> 
> Game works fine after a reboot with SaltyNX disabled under sysmodules

Same here. When loading Smash or Zelda, it crashes until I disable SaltyNX. Haven't tested other games, but I'm certain it happens with other titles as well. I'm on the 17.0.0 firmware.

**Comment by masagrator** [comment]
@Xalavar these games work fine. It's definitely issue on your side like not reading release notes.

**Comment by Xalavar** [comment]
Ah, never mind. It turns out that the culprit for me was some .elf file in the plugins folder. It's weird that it wasn't causing issues before the latest update though.

**Comment by masagrator** [comment]
Because before the latest update nx-fps and ReverseNX-RT were separated from SaltyNX. Now they are merged and using plugins that are doing the same thing cause issues. That's why I wrote to remove them.

**Comment by masagrator** [comment]
Added manually.
