### ISSUE TITLE
Super Mario Wonder don't start with SaltyNX

### ISSUE THREAD

**Issue by luislorenzocalvo** [masagrator/SaltyNX#39]
When I start the game with out it, it start fine, but with SaltyNX, it doesn't.
For the game to start, I need to delete the content file. Is with the only game that happend

**Comment by masagrator** [comment]
"content file" - you mean romfs mod?

**Comment by luislorenzocalvo** [comment]
I mean the files that are on the atmosphere of SaltyNX (sorry if I'm not explaining it good, I'm kind of newbe)
when I reffer to the content file I mean unistalling SaltyNX completly.

I don't really know how exception.txt works, I've put the game in it and still doesn't work.

![Captura de pantalla 2023-10-22 145013](https://github.com/masagrator/SaltyNX/assets/127310622/981ecaf8-a979-49d3-9fa5-0daf7944a28d)

**Comment by masagrator** [comment]
I have confirmation from trusted source that it works fine with this game.

![IMG_3516](https://github.com/masagrator/SaltyNX/assets/8557858/3d33729e-cd0d-4134-bdb3-b681fb14ec07)


Update SaltyNX, remove all elf files from SaltySD/plugins, remove unused custom sysmodules from atmosphere/contents and try again.

**Comment by luislorenzocalvo** [comment]
Could be the atmosphere version a problem? I'm in 1.5.4, with 0.7 SaltyNX.
I'll try updating the others sysmodules. Then I'll tell you if it is fixed or not.

**Comment by masagrator** [comment]
This is definitely not an atmosphere problem. Issue can be from using some sysmodule that conflicts with SaltyNX. So updating sysmodules you have may not solve the issue.

**Comment by luislorenzocalvo** [comment]
the thing is that Mario wonder is the only game that seems to have problems. And is something related to the content files of something, I'm trying to figure out what is it, because I deleted the content folder to play Mario Wonder, and now I want to use Tesla overlay again, so I'm trying to figure out what the problem is.

**Comment by luislorenzocalvo** [comment]
ok, now I'm going crazy, I've deleted everything, and it still doesn't start, I don't know what to do

**Comment by luislorenzocalvo** [comment]
ok, reinstalled mario wonder, it seems to work fine now, I'm going to see if it works with the sysmodules

**Comment by luislorenzocalvo** [comment]
now it works, I don't understand a shit💀

**Comment by luislorenzocalvo** [comment]
sorry for everything, maybe it needed to be reinstalled when I reinstalled tesla overlay and the sysmodules, I don't know
