### ISSUE TITLE
Crash on title launch for AMS1.6.2/HOS17.0

### ISSUE THREAD

**Issue by XLDS** [masagrator/SaltyNX#40]
Thread title,
crash on any title launch for all titles on Atmosphere 1.6.2 / Switch17.0 (emuMMC/sysMMC) SaltyNX error

Thank you for your time and blessing be upon you.
``Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                SaltyNX
    Program ID:                  0000000000534c56
    Process ID:                  0000000000000083
    Process Flags:               00000137
    User Exception Address:      0000006e282ab000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000400
    Fault Address:               0000000000000000
Crashed Thread Info:
    Thread ID:                   000000000000015f
    Stack Region:                0000006a608c3000-0000006a608c7000
    Registers:
        X[00]:                   0000000000000400
        X[01]:                   0000002db304fd40
        X[02]:                   0000000000000400
        X[03]:                   0000000000000400
        X[04]:                   0000002db3050140
        X[05]:                   0000000000000800
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000001
        X[19]:                   0000002db304e988
        X[20]:                   0000000000000400
        X[21]:                   0000000000000400
        X[22]:                   0000000000063088
        X[23]:                   0000000000063088
        X[24]:                   0000002db303a470
        X[25]:                   0000000000063488
        X[26]:                   0000000000063488
        X[27]:                   0000002db304fd40
        X[28]:                   0000000000000400
        FP:                      0000006a608c69f0
        LR:                      0000002db301d0f4 (saltysd_proc + 0x1d0f4)
        SP:                      0000006a608c69f0
        PC:                      0000002db301e678 (saltysd_proc + 0x1e678)
    Stack Trace:
        ReturnAddress[00]:       0000002db3005bd8 (saltysd_proc + 0x5bd8)
        ReturnAddress[01]:       0000002db3006440 (saltysd_proc + 0x6440)
        ReturnAddress[02]:       0000002db30005f0 (saltysd_proc + 0x5f0)
        ReturnAddress[03]:       0000002db30002e0 (saltysd_proc + 0x2e0)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 006a608c69f0 60 6a 8c 60 6a 00 00 00 d8 5b 00 b3 2d 00 00 00
                                 006a608c6a00 88 e9 04 b3 2d 00 00 00 f6 03 2c 00 00 00 00 00
                                 006a608c6a10 8e 00 00 00 00 00 00 00 80 fc 04 b3 2d 00 00 00
                                 006a608c6a20 88 34 06 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006a608c6a30 00 00 60 62 2c 00 00 00 d4 6f 8c 60 6a 00 00 00
                                 006a608c6a40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006a608c6a50 8e 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
                                 006a608c6a60 20 6f 8c 60 6a 00 00 00 40 64 00 b3 2d 00 00 00
                                 006a608c6a70 00 b2 2a 28 6e 00 00 00 a0 c8 03 b3 2d 00 00 00
                                 006a608c6a80 78 6f 8c 60 6a 00 00 00 7c 6f 8c 60 6a 00 00 00
                                 006a608c6a90 08 b2 2a 28 6e 00 00 00 40 42 0f 00 00 00 00 00
                                 006a608c6aa0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006a608c6ab0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006a608c6ac0 73 61 6c 74 79 73 64 5f 63 6f 72 65 2e 65 6c 66
                                 006a608c6ad0 00 00 00 00 00 00 00 00 53 61 6c 74 79 53 44 20
                                 006a608c6ae0 42 6f 6f 74 73 74 72 61 70 3a 20 45 4c 46 20 6c
    TLS Address:                 0000006e282ab200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 006e282ab200 00 00 00 00 0a 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab210 53 46 43 4f 00 00 00 00 00 00 00 00 a1 6d 71 f3
                                 006e282ab220 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab230 00 00 00 00 2c 00 00 00 00 04 00 00 00 00 00 00
                                 006e282ab240 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab250 53 61 6c 74 79 53 44 20 42 6f 6f 74 73 74 72 61
                                 006e282ab260 70 3a 20 45 4c 46 20 6c 6f 61 64 65 64 20 74 6f
                                 006e282ab270 20 25 70 0a 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab280 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           1
    Module 00:
        Address:                 0000002db3000000-0000002db3028000
        Name:                    saltysd_proc
        Module Id:               02FA1255412F636E57B5A0E904D0651A440112CB000000000000000000000000
Thread Report:
Number of Threads:               01
Threads[00]:
    Thread ID:                   000000000000015f
    Stack Region:                0000006a608c3000-0000006a608c7000
    Registers:
        X[00]:                   0000000000000400
        X[01]:                   0000002db304fd40
        X[02]:                   0000000000000400
        X[03]:                   0000000000000400
        X[04]:                   0000002db3050140
        X[05]:                   0000000000000800
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000001
        X[19]:                   0000002db304e988
        X[20]:                   0000000000000400
        X[21]:                   0000000000000400
        X[22]:                   0000000000063088
        X[23]:                   0000000000063088
        X[24]:                   0000002db303a470
        X[25]:                   0000000000063488
        X[26]:                   0000000000063488
        X[27]:                   0000002db304fd40
        X[28]:                   0000000000000400
        FP:                      0000006a608c69f0
        LR:                      0000002db301d0f4 (saltysd_proc + 0x1d0f4)
        SP:                      0000006a608c69f0
        PC:                      0000002db301e678 (saltysd_proc + 0x1e678)
    Stack Trace:
        ReturnAddress[00]:       0000002db3005bd8 (saltysd_proc + 0x5bd8)
        ReturnAddress[01]:       0000002db3006440 (saltysd_proc + 0x6440)
        ReturnAddress[02]:       0000002db30005f0 (saltysd_proc + 0x5f0)
        ReturnAddress[03]:       0000002db30002e0 (saltysd_proc + 0x2e0)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 006a608c69f0 60 6a 8c 60 6a 00 00 00 d8 5b 00 b3 2d 00 00 00
                                 006a608c6a00 88 e9 04 b3 2d 00 00 00 f6 03 2c 00 00 00 00 00
                                 006a608c6a10 8e 00 00 00 00 00 00 00 80 fc 04 b3 2d 00 00 00
                                 006a608c6a20 88 34 06 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006a608c6a30 00 00 60 62 2c 00 00 00 d4 6f 8c 60 6a 00 00 00
                                 006a608c6a40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006a608c6a50 8e 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
                                 006a608c6a60 20 6f 8c 60 6a 00 00 00 40 64 00 b3 2d 00 00 00
                                 006a608c6a70 00 b2 2a 28 6e 00 00 00 a0 c8 03 b3 2d 00 00 00
                                 006a608c6a80 78 6f 8c 60 6a 00 00 00 7c 6f 8c 60 6a 00 00 00
                                 006a608c6a90 08 b2 2a 28 6e 00 00 00 40 42 0f 00 00 00 00 00
                                 006a608c6aa0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006a608c6ab0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006a608c6ac0 73 61 6c 74 79 73 64 5f 63 6f 72 65 2e 65 6c 66
                                 006a608c6ad0 00 00 00 00 00 00 00 00 53 61 6c 74 79 53 44 20
                                 006a608c6ae0 42 6f 6f 74 73 74 72 61 70 3a 20 45 4c 46 20 6c
    TLS Address:                 0000006e282ab200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 006e282ab200 00 00 00 00 0a 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab210 53 46 43 4f 00 00 00 00 00 00 00 00 a1 6d 71 f3
                                 006e282ab220 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab230 00 00 00 00 2c 00 00 00 00 04 00 00 00 00 00 00
                                 006e282ab240 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab250 53 61 6c 74 79 53 44 20 42 6f 6f 74 73 74 72 61
                                 006e282ab260 70 3a 20 45 4c 46 20 6c 6f 61 64 65 64 20 74 6f
                                 006e282ab270 20 25 70 0a 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab280 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 006e282ab2f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
``

**Comment by masagrator** [comment]
1. What other sysmodules you have installed? 
2. Do you have latest SaltyNX installed?
3. What files you have in SaktySD/plugins folder?

**Comment by XLDS** [comment]
1. [DYNAMIC] sys-ftpd-light [off], Noexes [off], sys-con [off], sys-ftpd-10k [ON], sys-patch [off]
[STATIC] sys-clk [ON], SaltyNX [presently off], emuiibo [off], MissionControl [off], Fizeau [ON]

2. Unless something went horribly wrong, yes, I can double check again. The saltysd_core.elf has the same crc32 as the one in your latest release (0.7.0) (013E1198)

3. 0 files, 1 folder, present within root of SaltySD\, -  FPSlocker\patches\ with 2 .dat files present within FPSlocker\ root and the latest patches pack within patches\
![gogl3hI 1](https://github.com/masagrator/SaltyNX/assets/3269691/2d009087-c87b-43c1-9e1c-e5d8863804f5)

Let me know if you need to know anything else.
Thank you for your continued work on this project. It is of high value to a great deal of the community.

**Comment by masagrator** [comment]
Try to remove sys-ftpd from booting, restart Switch and try again.

**Comment by XLDS** [comment]
What the heck, that actually worked! Thank you so much for your help!!!

That's so weird I've never had trouble with the background ftp process in
the past...

Thank you again!

**Comment by masagrator** [comment]
sys-ftpd takes huge amount of RAM, so there was not enough for SaltyNX to work properly.
