### ISSUE TITLE
Issues with SaltyNX: Freezing and Unresponsiveness on Switch 16.1.0

### ISSUE THREAD

**Issue by joaopedromago** [masagrator/SaltyNX#45]
Whenever I add the SaltyNX atmosphere contents, my Switch behaves erratically. Here are the specific problems I'm encountering:

The status monitor freezes and I can't exit the screen unless I put the Switch into sleep mode and then close it.
The album sometimes freezes, necessitating a hard reset of the Switch.
Certain apps like JKSV also cause the Switch to freeze.
None of these problems does not occur when I uninstall SaltyNX.

System Information:

SaltyNX Version: 0.7.1
Switch Firmware Version: 16.1.0
Atmosphere Version: 1.6.2

SaltySD/plugins have already been deleted.

I hope this information helps in diagnosing and resolving these issues. Thank you for your attention to this matter.

**Comment by masagrator** [comment]
You didn't list all sysmodules you have installed. And my assumption is that you have exhausted space for sysmodules, so adding SaltyNX to pool is breaking system.

**Comment by masagrator** [comment]
No response for more than a month. Closing.
