### ISSUE TITLE
Noticeable overhead (stuttering) in some games using dynamic resolution

### ISSUE THREAD

**Issue by xick** [masagrator/SaltyNX#46]
Hi, I noticed a significant drop in performance in a specific game when SaltyNX is active. While disabled, the game is running consistently, when the module is on games has severe drop in fps. I can tell for sure this game uses Dynamic Resolution and frame timing stats, so my guess it's somehow interfering with frame stats readings. 
I am opening the issue mainly to let other knows that there is a possibility fps reading could cause extra overhead in some games. Also I wish to know if anyone else has experienced this behaviour with other games.

**Comment by masagrator** [comment]
Hi.
By hiding informations your issue is not very helpful. Why not provide titles of those games?
Beside provide SaltyNX version, confirm that you have no elf files in SaltySD/plugins and no exefs mods installed in those games.

**Comment by xick** [comment]
My mistake, the stuttering was caused by a fpslocker patch (probably was messing with buffering window). Sorry, I closed the issue :)
