### ISSUE TITLE
Smash Ultimate Crash

### ISSUE THREAD

**Issue by dachimiriani** [masagrator/SaltyNX#5]
Hi,
When I launch Smash Ultimate with some plugins, the game just crashes. And after re-launching the game, there are no plugins active.
Please help resolve this issue.
Thanks.

**Comment by masagrator** [comment]
Well:
- CFW?
- List of all used sysmodules with versions
- is SaltyNX you are using the newest one
- Games you have tested
- Is SaltyNX-Tool showing that SaltyNX is properly injected

Start from this.

**Comment by dachimiriani** [comment]
1. CFW: Atmosphere/ NeutOS
2. sysmodules: EdiZon (1.0.0), Tesla Example (1.0.0), emuiibo (0.5.0), Sysmodules (1.2.1)
3. SaltyNX v0.3.1a.

**Comment by masagrator** [comment]
```
No technical support for:

- Atmosphere forks
```

**Comment by Genwald** [comment]
I have heard others complaining of this in the Smash Ultimate modding discord. 0.2.1a is the last that we've found to work, so that's what we are recommending people use.

**Comment by masagrator** [comment]
> I have heard others complaining of this in the Smash Ultimate modding discord on standard atmos. 0.2.1a is the last that we've found to work, so that's what we are recommending people use.

Create new issue with plugin example that will be visible from the beginning. I need to reproduce issue to start from somewhere.
