### ISSUE TITLE
Crash - The Legend of Zelda: Echoes of Wisdom

### ISSUE THREAD

**Issue by ZweiBR** [masagrator/SaltyNX#53]
Crash at exit game

**Comment by masagrator** [comment]
Explain to me how did you deduce this is related to SaltyNX.

**Comment by ZweiBR** [comment]
> Explain to me how did you deduce this is related to SaltyNX.

https://a.imagem.app/3uMFAi.jpeg
https://a.imagem.app/3uMX18.jpeg
https://a.imagem.app/3uMxtE.jpeg

The game file is OK as shown in DBi.
BY adding the game line the crash no longer exists.
The problem is when I do this my FPS no longer shows in the game in question.

**Comment by AK478BB** [comment]
add it in exceptions.txt as follows

;The Legend of Zelda: Echoes of Wisdom
;1.0.1 Crash
X01008CF01BAAC000

**Comment by AK478BB** [comment]
or you can set saltynx off in background services by hekatetoolbox.nro

**Comment by masagrator** [comment]
> or you can set saltynx off in background services by hekatetoolbox.nro

Or you can just use SaltyNX-Tool so you won't need to restart Switch ¯\_(ツ)_/¯

**Comment by ZweiBR** [comment]
> > or you can set saltynx off in background services by hekatetoolbox.nro
> 
> Or you can just use SaltyNX-Tool so you won't need to restart Switch ¯\_(ツ)_/¯

I reported the game issue.
Thank you for your work

**Comment by masagrator** [comment]
Well, I won't have this game for like next 2 weeks, so good luck out there. o7

**Comment by masagrator** [comment]
0.9.3 release fixed crashing at the cost of disabling ReverseNX-RT in this game. Use ReverseNX-Tool instead.
