### ISSUE TITLE
Never got it to work

### ISSUE THREAD

**Issue by karimps** [masagrator/SaltyNX#55]
Ever since NX-FPS got included I never ever got it to work again no matter what. 

Atmosphere 1.7.1
NS FW 18.0.1 

Installed all needed bits on 2 different consoles to no avail... dont know what to do next

**Comment by masagrator** [comment]
Ever since then did you read release notes even once, excluding latest release?

**Comment by karimps** [comment]
Of course I did, I even followed some instruction list written by you in order to get FPS to work. Don't know what I'm missing. 

Any more complete list of what to do from start to finish? 

Thank you for your support and awesome contributions

**Comment by masagrator** [comment]
Remove log files from SaltySD folder, restart Switch, run game and send me generated both log files.

**Comment by karimps** [comment]
I can only see one log file and one exception file 

log.flag is empty 

![Screenshot 2024-10-21 130436](https://github.com/user-attachments/assets/4ad48f1f-1d41-4b23-a1d1-8f26efe1c8e9)
[exceptions.txt](https://github.com/user-attachments/files/17459744/exceptions.txt)
[saltysd.log](https://github.com/user-attachments/files/17459745/saltysd.log)

**Comment by masagrator** [comment]
1. this log shows me you did more than I asked. Do it exactly as someone told you, I guess you were using either status monitor or fpslocker.
2. Something is blocking debugevent, which usually go down to one thing - delete from contents everything except for SaltyNX and try again. This can be third party debugger, plug-in with main.npdm having wrong debug flags, etc.

**Comment by karimps** [comment]
OK. I got it to work, don't know how but got it to work. 

Thank you for your assistance
