### ISSUE TITLE
Super Smash Bros. Ultimate crash at game runtime

### ISSUE THREAD

**Issue by ThatNintendoNerd** [masagrator/SaltyNX#7]
Upon launching the game it never makes it past the Switch game loading screen before crashing. Loading the game a second time seems to launch the game successfully, however no plugins are loaded. SaltyNX-Tool states that it is injected properly and is enabled. I am on:

- Stock Atmosphère 0.13.0 sysMMC
- Firmware 10.0.4
- SaltyNX 0.3.1a
- Sysmodules: sys-ftpd-light
- Skyline [plugin](https://github.com/jam1garner/replace_music) for game

If it helps for whatever reason, a custom theme is being used too, however this has caused no problems in the time I have had it installed. Here is a clean crash report folder along with SaltyNX logs with only what is created by the latest SaltyNX release: [cross2_crash.zip](https://github.com/masagrator/SaltyNX/files/4936189/cross2_crash.zip). This is the only [plugin](https://gamebanana.com/gamefiles/12226) being used in question for replication purposes, however it should also crash with any other plugin. The archive bit has been unset entirely on at least the `SaltySD` folder.

You may have heard from the past but from testing by the Smash Ultimate Modding Hub Discord server, 0.2.1a was the last known working version to load plugins for Smash. If any more testing is necessary on my end I can do so.

**Comment by masagrator** [comment]
Skyline plugins are not meant for SaltyNX. Read Skyline specification to learn more.

I've heard about crashing Smash, but noone until now created proper issue on github, so I didn't bother to check.

I will look into it in free time.

**Comment by ThatNintendoNerd** [comment]
Thank you. I am well aware that Skyline plugins are not meant for SaltyNX and that they use entirely different formats, however I thought I should mention everything that I'm using in the event that it had an effect on the crash logs or such for one reason or another.

**Comment by masagrator** [comment]
So I have checked game with 8.0.0 version, NX-FPS and ReverseNX-RT. No crashes, everything works as expected.
After trying your plugin I got crash. After simple test I found out that issue lays in introduced by me in 0.3.0a bug with importing plugins from titleid folders. You can just move togglefly.elf from 01006A800016E000 to plugins folder, delete 01006A800016E000 and nothing crashes. 

It should be easy to fix.

**Comment by masagrator** [comment]
Ok, I got it fixed on my unit.
Try this. After positive confirmation I will release it.

[SaltyNX-0.3.2a.zip](https://github.com/masagrator/SaltyNX/files/4943403/SaltyNX-0.3.2a.zip)

**Comment by ThatNintendoNerd** [comment]
Confirmed it does work! No crash at runtime and the plugin takes effect as intended. Thank you for fixing this issue.
